services:      
  producer:
    build:
      context: ./website
    container_name: producer
    ports:
      - 6000:6000

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=NA
      - DOCKER_INFLUXDB_INIT_BUCKET=events
      - DOCKER_INFLUXDB_INIT_RETENTION=2d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=abcdef
    volumes:
      - INFLUXDB-DATA:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - GRAFANA-DATA:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  INFLUXDB-DATA:
    name: influxdb_data
  GRAFANA-DATA:
    name: grafana_data